#!/bin/bash
sudo apt-get install -y mongodb-org
sudo apt-get install --only-upgrade mongodb
echo "mongodb has been installed successfully!"
sudo apt-get install ruby-full
sudo apt-get install --only-upgrade ruby
echo "Ruby has been installed successfully!"

service=mongod
if (( $(ps -ef | grep -v grep | grep $service| wc -l) > 0))
then
echo "$service is running!!!"
else
service mongod start
echo "mongodb is started"
fi
mongoimport --db hashSample --collection backdoor --file db.json
